/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/I1tADIEhF2Q
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Calendar } from "@/components/ui/calendar"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Link } from "@nextui-org/react"

export function SpecialistPage() {
  return (
    <div className="flex flex-col w-full min-h-screen bg-muted">
      <header className="bg-primary text-primary-foreground py-8 px-4 md:px-6">
        <div className="container mx-auto flex items-center gap-4">
          <div className="flex-shrink-0 rounded-full w-16 h-16 bg-primary-foreground/20 flex items-center justify-center text-4xl font-bold">
            JD
          </div>
          <div className="flex-1">
            <h1 className="text-2xl font-bold">John Doe</h1>
            <p className="text-sm text-primary-foreground/80">ID: #12345</p>
          </div>
        </div>
      </header>
      <main className="container mx-auto grid grid-cols-1 md:grid-cols-2 gap-8 py-12 px-4 md:px-6">
        <section>
          <h2 className="text-xl font-bold mb-4">Contact and Location</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <h3 className="text-base font-semibold mb-2">Address</h3>
              <address className="text-sm text-muted-foreground not-italic">123 Main Street, Anytown USA</address>
            </div>
            <div>
              <h3 className="text-base font-semibold mb-2">Contact</h3>
              <div className="text-sm text-muted-foreground">
                <p>Phone: +1 (123) 456-7890</p>
                <p>Email: johndoe@example.com</p>
              </div>
            </div>
          </div>
          <div className="mt-4">
            <iframe
              src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3022.1422937950147!2d-73.98731268482413!3d40.7501605793276!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25855c6480299%3A0x55194ec5a1ae072e!2sEmpire%20State%20Building!5e0!3m2!1sen!2sus!4v1593528295726!5m2!1sen!2sus"
              width="100%"
              height="300"
              frameBorder="0"
              style={{ border: 0 }}
              allowFullScreen
              aria-hidden="false"
              tabIndex={0}
            />
          </div>
        </section>
        <section>
          <h2 className="text-xl font-bold mb-4">Services Offered</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="bg-background rounded-lg p-4">
              <h3 className="text-base font-semibold mb-2">Haircut</h3>
              <p className="text-sm text-muted-foreground">$25 - 30 mins</p>
            </div>
            <div className="bg-background rounded-lg p-4">
              <h3 className="text-base font-semibold mb-2">Color</h3>
              <p className="text-sm text-muted-foreground">$80 - 2 hrs</p>
            </div>
            <div className="bg-background rounded-lg p-4">
              <h3 className="text-base font-semibold mb-2">Highlights</h3>
              <p className="text-sm text-muted-foreground">$60 - 1.5 hrs</p>
            </div>
            <div className="bg-background rounded-lg p-4">
              <h3 className="text-base font-semibold mb-2">Blowout</h3>
              <p className="text-sm text-muted-foreground">$40 - 45 mins</p>
            </div>
          </div>
        </section>
        <section>
          <h2 className="text-xl font-bold mb-4">Booking</h2>
          <div className="bg-background rounded-lg p-4">
            <Calendar
              numberOfMonths={1}
              mode="range"
              className="p-0 [&_td]:w-10 [&_td]:h-10 [&_th]:w-10 [&_[name=day]]:w-10 [&_[name=day]]:h-10 [&>div]:space-x-0 [&>div]:gap-6"
            />
            <div className="mt-4">
              <Select>
                <SelectTrigger className="h-auto">
                  <SelectValue
                    placeholder={
                      <div className="flex flex-col items-start">
                        <span className="font-semibold uppercase text-[0.65rem]">Service</span>
                        <span className="font-normal">Haircut</span>
                      </div>
                    }
                  />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="haircut">Haircut</SelectItem>
                  <SelectItem value="color">Color</SelectItem>
                  <SelectItem value="highlights">Highlights</SelectItem>
                  <SelectItem value="blowout">Blowout</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="mt-4">
              <Button size="lg" className="w-full">
                Book Now
              </Button>
            </div>
          </div>
        </section>
        <section>
          <h2 className="text-xl font-bold mb-4">Working Hours</h2>
          <div className="bg-background rounded-lg p-4">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-base font-semibold mb-2">Monday - Friday</h3>
                <p className="text-sm text-muted-foreground">9:00 AM - 6:00 PM</p>
              </div>
              <div className="bg-green-500 text-green-50 px-2 py-1 rounded-full text-xs font-semibold">Open</div>
            </div>
            <Separator className="my-4" />
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-base font-semibold mb-2">Saturday</h3>
                <p className="text-sm text-muted-foreground">10:00 AM - 4:00 PM</p>
              </div>
              <div className="bg-green-500 text-green-50 px-2 py-1 rounded-full text-xs font-semibold">Open</div>
            </div>
            <Separator className="my-4" />
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-base font-semibold mb-2">Sunday</h3>
                <p className="text-sm text-muted-foreground">Closed</p>
              </div>
              <div className="bg-red-500 text-red-50 px-2 py-1 rounded-full text-xs font-semibold">Closed</div>
            </div>
          </div>
        </section>
        <section>
          <h2 className="text-xl font-bold mb-4">Gallery</h2>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
            <img
              src="/placeholder.svg"
              width={200}
              height={200}
              alt="Gallery Image"
              className="rounded-lg object-cover aspect-square"
            />
            <img
              src="/placeholder.svg"
              width={200}
              height={200}
              alt="Gallery Image"
              className="rounded-lg object-cover aspect-square"
            />
            <img
              src="/placeholder.svg"
              width={200}
              height={200}
              alt="Gallery Image"
              className="rounded-lg object-cover aspect-square"
            />
            <img
              src="/placeholder.svg"
              width={200}
              height={200}
              alt="Gallery Image"
              className="rounded-lg object-cover aspect-square"
            />
            <img
              src="/placeholder.svg"
              width={200}
              height={200}
              alt="Gallery Image"
              className="rounded-lg object-cover aspect-square"
            />
            <img
              src="/placeholder.svg"
              width={200}
              height={200}
              alt="Gallery Image"
              className="rounded-lg object-cover aspect-square"
            />
          </div>
        </section>
        <section>
          <h2 className="text-xl font-bold mb-4">Reviews and Ratings</h2>
          <div className="bg-background rounded-lg p-4">
            <div className="flex items-center gap-2">
              <div className="flex items-center gap-1">
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-muted-foreground" />
              </div>
              <div className="text-base font-semibold">4.2</div>
              <div className="text-sm text-muted-foreground">(124 reviews)</div>
            </div>
            <Separator className="my-4" />
            <div className="space-y-4">
              <div className="flex items-start gap-4">
                <Avatar className="w-10 h-10 border">
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="flex-1">
                  <div className="flex items-center justify-between">
                    <div className="font-semibold">Jane Doe</div>
                    <div className="text-sm text-muted-foreground">2 days ago</div>
                  </div>
                  <p className="text-sm text-muted-foreground">
                    I had a great experience with John. He was very professional and my haircut turned out exactly how I
                    wanted it.
                  </p>
                </div>
              </div>
              <div className="flex items-start gap-4">
                <Avatar className="w-10 h-10 border">
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="flex-1">
                  <div className="flex items-center justify-between">
                    <div className="font-semibold">John Smith</div>
                    <div className="text-sm text-muted-foreground">1 week ago</div>
                  </div>
                  <p className="text-sm text-muted-foreground">
                    I've been coming to John for years and he always does an amazing job. Highly recommended!
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section>
          <h2 className="text-xl font-bold mb-4">About</h2>
          <div className="bg-background rounded-lg p-4">
            <p className="text-sm text-muted-foreground">
              John Doe is a highly skilled and experienced barber/hairstylist with over 10 years of expertise in the
              industry. He specializes in precision haircuts, color treatments, and styling for both men and women. John
              is known for his attention to detail, creative flair, and exceptional customer service. He is constantly
              updating his skills and techniques to stay at the forefront of the latest trends and innovations in the
              field.
            </p>
          </div>
        </section>
      </main>
      <footer className="bg-primary text-primary-foreground py-4 px-4 md:px-6">
        <div className="container mx-auto flex items-center justify-between">
          <div className="text-sm">&copy; 2024 br10 Inc. All rights reserved.</div>
          <div className="flex items-center gap-4">
            <Link href="#" className="text-sm hover:underline">
              Terms of Service
            </Link>
            <Link href="#" className="text-sm hover:underline">
              Privacy Policy
            </Link>
          </div>
        </div>
      </footer>
    </div>
  )
}

function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}


// function XIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M18 6 6 18" />
//       <path d="m6 6 12 12" />
//     </svg>
//   )
// }
