/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/60Hm7Cpj5wy
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

 import { Libre_Franklin } from 'next/font/google'

 libre_franklin({
 subsets: ['latin'],
 display: 'swap',
 })

 To read more about using these font, please visit the Next.js documentation:
 - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
 - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
 **/
import {Avatar, AvatarFallback, AvatarImage} from "@/components/ui/avatar"
import {Button} from "@/components/ui/button"
import {useParams} from "react-router-dom";

export function UserProfilePage() {
    // get path variable from the URL with name userName

    const {param} = useParams<{ param: string }>();


    return (
        <div className="w-full max-w-4xl mx-auto p-6 md:p-10">
            <div className="grid grid-cols-1 md:grid-cols-[200px_1fr] gap-6 md:gap-10">
                <div className="flex flex-col items-center gap-4">
                    <Avatar className="w-24 h-24 border-2 border-primary">
                        <AvatarImage src="/placeholder-user.jpg"/>
                        <AvatarFallback>JD</AvatarFallback>
                    </Avatar>
                    <div className="text-center">
                        <h2 className="text-2xl font-bold">{param}</h2>
                        <div className="text-muted-foreground">
                            <a href="#" className="hover:underline">
                                +1 (234) 567-890
                            </a>
                            <span className="mx-2">|</span>
                            <a href="#" className="hover:underline">
                                john@example.com
                            </a>
                        </div>
                    </div>
                </div>
                <div className="grid gap-6">
                    <div>
                        <h3 className="text-xl font-semibold mb-4">Past Bookings</h3>
                        <div className="grid gap-4">
                            <div className="bg-muted p-4 rounded-lg">
                                <div className="flex justify-between items-center mb-2">
                                    <div className="font-medium">Haircut</div>
                                    <div className="text-muted-foreground text-sm">June 15, 2023 - 10:00 AM</div>
                                </div>
                                <div className="flex justify-between items-center">
                                    <div className="flex items-center gap-2">
                                        <Avatar className="w-8 h-8 border">
                                            <AvatarImage src="/placeholder-user.jpg"/>
                                            <AvatarFallback>JD</AvatarFallback>
                                        </Avatar>
                                        <div>
                                            <div className="font-medium">Jane Doe</div>
                                            <div className="text-muted-foreground text-sm">Barber ID: 12345</div>
                                        </div>
                                    </div>
                                    <div>
                                        <Button variant="ghost" size="icon" className="rounded-full">
                                            <HeartIcon className="w-5 h-5"/>
                                            <span className="sr-only">Favorite</span>
                                        </Button>
                                    </div>
                                </div>
                            </div>
                            <div className="bg-muted p-4 rounded-lg">
                                <div className="flex justify-between items-center mb-2">
                                    <div className="font-medium">Shave</div>
                                    <div className="text-muted-foreground text-sm">May 30, 2023 - 2:00 PM</div>
                                </div>
                                <div className="flex justify-between items-center">
                                    <div className="flex items-center gap-2">
                                        <Avatar className="w-8 h-8 border">
                                            <AvatarImage src="/placeholder-user.jpg"/>
                                            <AvatarFallback>JD</AvatarFallback>
                                        </Avatar>
                                        <div>
                                            <div className="font-medium">John Smith</div>
                                            <div className="text-muted-foreground text-sm">Barber ID: 54321</div>
                                        </div>
                                    </div>
                                    <div>
                                        <Button variant="ghost" size="icon" className="rounded-full">
                                            <HeartIcon className="w-5 h-5"/>
                                            <span className="sr-only">Favorite</span>
                                        </Button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div>
                        <h3 className="text-xl font-semibold mb-4">Upcoming Bookings</h3>
                        <div className="bg-muted p-4 rounded-lg">
                            <div className="flex justify-between items-center mb-2">
                                <div className="font-medium">Haircut</div>
                                <div className="text-muted-foreground text-sm">July 1, 2023 - 3:00 PM</div>
                            </div>
                            <div className="flex justify-between items-center">
                                <div className="flex items-center gap-2">
                                    <Avatar className="w-8 h-8 border">
                                        <AvatarImage src="/placeholder-user.jpg"/>
                                        <AvatarFallback>JD</AvatarFallback>
                                    </Avatar>
                                    <div>
                                        <div className="font-medium">Jane Doe</div>
                                        <div className="text-muted-foreground text-sm">Barber ID: 12345</div>
                                    </div>
                                </div>
                                <div className="flex gap-2">
                                    <Button variant="outline" size="sm">
                                        Reschedule
                                    </Button>
                                    <Button variant="destructive" size="sm">
                                        Cancel
                                    </Button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div>
                        <h3 className="text-xl font-semibold mb-4">Feedback</h3>
                        <div className="bg-muted p-4 rounded-lg">
                            <div className="flex justify-between items-center mb-2">
                                <div className="flex items-center gap-2">
                                    <Avatar className="w-8 h-8 border">
                                        <AvatarImage src="/placeholder-user.jpg"/>
                                        <AvatarFallback>JD</AvatarFallback>
                                    </Avatar>
                                    <div>
                                        <div className="font-medium">Jane Doe</div>
                                        <div className="text-muted-foreground text-sm">Barber ID: 12345</div>
                                    </div>
                                </div>
                                <div className="flex items-center gap-1">
                                    <StarIcon className="w-5 h-5 fill-primary"/>
                                    <StarIcon className="w-5 h-5 fill-primary"/>
                                    <StarIcon className="w-5 h-5 fill-primary"/>
                                    <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground"/>
                                    <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground"/>
                                </div>
                            </div>
                            <div className="text-sm text-muted-foreground">
                                Great experience! Jane was very professional and did an amazing job with my haircut.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

function HeartIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path
                d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"/>
        </svg>
    )
}


function StarIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <polygon
                points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/>
        </svg>
    )
}


function XIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M18 6 6 18"/>
            <path d="m6 6 12 12"/>
        </svg>
    )
}
